version: '2.1'
services:
  dev-los-bichanos:
    image: starefossen/ruby-node:latest
    volumes:
     - ./:/var/www/app/
     - "${HOME}/.cache/yarn:/root/.cache/yarn"
    working_dir: /var/www/app/
    ports:
     - "3001:3001"
     - "8081:8081"
    command: bash -c "npm install -g gulp && yarn install && gulp --folder los-bichanos"
